import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import dashboardRouter from "./dashboard";
import rolesRouter from "./roles";
import teachersRouter from "./teachers";
import studentsRouter from "./students";
import subjectsRouter from "./subjects";
import documentsRouter from "./documents";
import tujuanPembelajaranRouter from "./tujuan-pembelajaran";
import journalRouter from "./journal";
import attendanceRouter from "./attendance";
import gradesRouter from "./grades";
import pointsRouter from "./points";
import academicCalendarsRouter from "./academic-calendars";
import prosemRouter from "./prosem";
import infoPekananRouter from "./info-pekanan";
import modulAjarRouter from "./modul-ajar";
import soalOtomatisRouter from "./soal-otomatis";
import studentAccountsRouter from "./student-accounts";
import feedbackRouter from "./feedback";
import bahanAjarRouter from "./bahan-ajar";
import debugProsemRouter from "./debug-prosem";
import jadwalRouter from "./jadwal";
import rekapRouter from "./rekap";
import inboxRouter from "./inbox";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(dashboardRouter);
router.use(rolesRouter);
router.use(teachersRouter);
router.use(studentsRouter);
router.use(subjectsRouter);
router.use(documentsRouter);
router.use(tujuanPembelajaranRouter);
router.use(journalRouter);
router.use(attendanceRouter);
router.use(gradesRouter);
router.use(pointsRouter);
router.use(academicCalendarsRouter);
router.use(prosemRouter);
router.use(infoPekananRouter);
router.use(modulAjarRouter);
router.use(soalOtomatisRouter);
router.use(studentAccountsRouter);
router.use(feedbackRouter);
router.use(bahanAjarRouter);
router.use(debugProsemRouter);
router.use(jadwalRouter);
router.use(rekapRouter);
router.use(inboxRouter);

export default router;
