// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/gamifikasi/InsightGuru.tsx": () => import("../components/mockups/gamifikasi/InsightGuru.tsx"),
  "./components/mockups/gamifikasi/LencanaPencapaian.tsx": () => import("../components/mockups/gamifikasi/LencanaPencapaian.tsx"),
  "./components/mockups/gamifikasi/PapanPeringkat.tsx": () => import("../components/mockups/gamifikasi/PapanPeringkat.tsx"),
  "./components/mockups/gamifikasi/TokoKoin.tsx": () => import("../components/mockups/gamifikasi/TokoKoin.tsx"),
  "./components/mockups/hafalan/GuruPanel.tsx": () => import("../components/mockups/hafalan/GuruPanel.tsx"),
  "./components/mockups/hafalan/Leaderboard.tsx": () => import("../components/mockups/hafalan/Leaderboard.tsx"),
  "./components/mockups/hafalan/PapanPeringkat.tsx": () => import("../components/mockups/hafalan/PapanPeringkat.tsx"),
  "./components/mockups/hafalan/SiswaProfil.tsx": () => import("../components/mockups/hafalan/SiswaProfil.tsx"),
  "./components/mockups/tomat-screens/GameUI.tsx": () => import("../components/mockups/tomat-screens/GameUI.tsx"),
  "./components/mockups/tomat-screens/GuruDash.tsx": () => import("../components/mockups/tomat-screens/GuruDash.tsx"),
  "./components/mockups/tomat-screens/GuruDashVariantA.tsx": () => import("../components/mockups/tomat-screens/GuruDashVariantA.tsx"),
  "./components/mockups/tomat-screens/GuruDashVariantB.tsx": () => import("../components/mockups/tomat-screens/GuruDashVariantB.tsx"),
  "./components/mockups/tomat-screens/Login.tsx": () => import("../components/mockups/tomat-screens/Login.tsx"),
  "./components/mockups/tomat-screens/LoginVariantA.tsx": () => import("../components/mockups/tomat-screens/LoginVariantA.tsx"),
  "./components/mockups/tomat-screens/LoginVariantB.tsx": () => import("../components/mockups/tomat-screens/LoginVariantB.tsx"),
  "./components/mockups/tomat-screens/LoginVariantC.tsx": () => import("../components/mockups/tomat-screens/LoginVariantC.tsx"),
  "./components/mockups/tomat-screens/Profile.tsx": () => import("../components/mockups/tomat-screens/Profile.tsx"),
  "./components/mockups/tomat-screens/SiswaHome.tsx": () => import("../components/mockups/tomat-screens/SiswaHome.tsx")
};
